name: easy_compass
description: A Flutter package for accessing and displaying compass heading information.
version: 0.0.1
homepage: https://github.com/tajaouart/easy_compass

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^2.0.5
  mockito: ^5.4.0


dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
